### ISSUE TITLE
Migration framework for MongoDB

### ISSUE THREAD

**Issue by pingvinen** [rapidcore/issues#12]
It should support running arbitrary code (focused on updating the state of the database).

Supporting migration in both directions would be nice (i.e. upgrading and downgrading).

Some would argue that this is not necessary with a schema-less db like Mongo, but that argument is based on a view that a migration only does changing of a "table"-definition. A migration might also run code to update values in the db though.

It cannot guarantee that the migrations written are re-entrant, but it should protect against running the same migrations multiple times. It should still be "easy" to get it to forget a migration though (for those times where a migration fails to do the right thing etc. - you know, reality :)

**Comment by pingvinen** [comment]
Follow up "question": How to handle a system that has multiple databases (i.e. multiple connections). Should a migration stack be maintained for each connection or should the migration stack include a way to switch between dbs (multiplexing)?

One idea for multiplexing could be that the migration stack has a `IConnectionProvider` where connections are registered by name. Then the migration code can refer to different databases by name.

**Comment by MartinsRui** [comment]
Tentative plan for alpha:

- [x] Base class/ Interface
- [x] Mark migration as done in DB
- [x] Support Up/Down
- [x] Configurable container
- [ ] Migration functions: RenameProp/RenameCol/ Drop * /Add * / Indexes
- [x] Reentry migrations
- [x] Lock
- [ ] Cli tool
- [x] Documentation (rapidcore/docs#2)
- [ ] Support for validating whether there are any pending migrations, like implemented here for EF: https://stackoverflow.com/questions/37562122/is-there-a-way-to-run-ef-core-rc2-tools-from-published-dll/43603140#43603140 
- [ ] Support for migration "consolidation" - i.e if the developers have deleted old migrations from the source, remove the corresponding migrations from the state collection `__RapidCoreMigrations`
