### ISSUE TITLE
Add Mongodb distributed app lock

### ISSUE THREAD

**Issue by nover** [rapidcore/issues#13]
According to this slide deck it should be possible to implement a distributed app lock using mongo:
https://speakerdeck.com/raindev/distributed-locking-with-mongodb

This will be useful for #12 before trying to apply migrations.

**Comment by nover** [comment]
https://www.codeproject.com/Articles/1035844/Exclusive-lock-in-distributed-solutions-with-Mongo

**Comment by pingvinen** [comment]
Moved to rapidcore/rapidcore#29
